#!/bin/sh

PROG_NAME=iBackup
if [ -n "$TMUX" ]; then
	tmux rename-window "$PROG_NAME"
	trap 'tmux rename-window "$PROG_NAME finished"' EXIT
else
	printf '\033]0;%s\007' $PROG_NAME
	trap 'printf "\033]0;%s\007" "$PROG_NAME finished"' EXIT
fi

folder=/media/Backup/MobileSync
netmuxd=netmuxd-x86_64-linux-gnu

# cd "$folder"

"$folder/$netmuxd" --disable-unix --host 127.0.0.1 &
pid=$!

# Wait a little bit until netmuxd finds device
sleep 10

# Start (incremental) backup
USBMUXD_SOCKET_ADDRESS=127.0.0.1:27015 OPENSSL_CONF="$folder/openssl-weak.conf" time idevicebackup2 backup -n --full "$folder"

kill $pid

