#!/bin/sh

folder=/usr/local/bin
netmuxd=netmuxd-x86_64-linux-gnu



echo "Getting netmuxd binary..."

latest_netmuxd=`wget -q -O - https://api.github.com/repos/jkcoxson/netmuxd/releases/latest | jq -r '.assets[].browser_download_url' | grep $netmuxd`

wget -q $latest_netmuxd -O "$folder/$netmuxd"

chmod a+x "$folder/$netmuxd"


